services:
  frontend:
    image: nextgencrypto_frontend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.frontend
      args:
        - VITE_BACKEND_BASEURL=http://188.166.165.112:5555/
    restart: always
    ports:
      - 80:80
    

  backend:
    image: nextgencrypto_backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.backend
    restart: always
    ports:
      - 5555:5555
    

